language: java

addons:
  apt:
    packages:
      - sshpass

after_success:
  - mkdir build
  - mv * build
  - tar -czf newbuild.tgz build
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp newbuild.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH

