language: java

addons:
  apt:
    packages:
      - sshpass

after_success:
  - mkdir buildtodeploy
  - mv * buildtodeploy
  - tar -czf newbuild.tgz buildtodeploy
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp newbuild.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH

