language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - sshpass

after_success:
  - mkdir build
  - cd ..
  - tar -czf newbuild.tgz *
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp -o stricthostkeychecking=no newbuild.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh $DEPLOY_USERNAME@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

